# Introduction {#financialisation-grains-intro}

In the early 2000s, against a backdrop of a low yield environment and poor stock market performance, the investment industry developed financial products designed for providing individuals and institutions with buy-side exposure to commodities through over-the-counter (OTC) swaps, exchange-traded funds (ETFs), and exchange-traded notes (ETNs), all of which are linked to popular commodity indexes such as the Goldman Sachs Commodity Index (S&P-GSCI). As these products grew in popularity investment in long-only commodity index funds rapidly soared^[Assets allocated to commodity index replication strategies grew from $13bn in 2003 to over \$300bn in 2008 [@masters_accidental_2011].]. Some refer to this large inflow of mostly institutional capital and its impact as the financialisation of commodity markets [@domanski_financial_2007]. The issue has had a wide impact on areas ranging from financial^[For example @tang_index_2012, @singleton_investor_2013, @basak_model_2016, @henderson_new_2015.] and agricultural^[@irwin_financialisation_2012 study the impact on agricultural markets, @irwin_index_2011 and @hamilton_effects_2015  on commodity markets in general, @buyuksahin_speculators_2014 study the oil market while @korniotis_does_2009 considers the metals market.] economics to public policy^[The first responses to the 2007/2008 crisis of escalating food and energy prices took the form of policy reports, many of which reasoned that the growth of commodity index funds came along with an influx of largely speculative capital that was responsible for driving commodity prices beyond their historic highs [@senate_excessive_2009; @unctad_global_2009; @herman_not_2011; @deschutter_food_2010; @schumann_hunger_2011].] and revived the long-standing "adequacy of speculation" debate. Agricultural commodities have been the forefront of the controversy over whether "excess speculation", allegedly brought about by financialisation, has contributed to price spikes in commodity markets^[@irwin_index_2011; @rouwenhorst_commodity_2012; @cheng_financialisation_2014 and @bos_bitter_2012 survey the literature and summarize the policy and academic debates.]. On one side, championed by hedge fund manager Michael Masters, are those who argue that index investor driven buying pressure created a massive bubble in commodity prices^[This contention is commonly referred to as the Masters' Hypothesis.], particularly in the grain and energy markets [@masters_testimony_2008; @masters_accidental_2011; @caballero_financial_2008; @petzel_testimony_2009; @hamilton_causes_2009; @du_financial_2017]. Others, advocated by the academic duo formed by Dwight Sanders and Scott Irwin, are dismissive of this contention and point out inconsistencies as well as contradictory facts in the bubble arguments [@krugman_more_2008; @pirrong_restricting_2008; @pirrong_no_2010; @sanders_futures_2008; @irwin_devil_2009; @korniotis_does_2009; @harris_role_2009; @till_has_2009; @stoll_commodity_2010]. A number of academic studies attempted to sort out which side of the debate is correct using a variety of economic tools^[While @gilbert_speculative_2010, @gilbert_how_2010, @phillips_explosive_2011, @phillips_dating_2011, @tang_index_2012 are supportive of the bubble argument, @harris_role_2009, @brunetti_is_2009, @sanders_adequacy_2010, @stoll_commodity_2010, @sanders_speculative_2010, @sanders_adequacy_2010, @sanders_impact_2011, @irwin_testing_2012, @buyuksahin_speculators_2014, @kilian_role_2014 dismiss it.]. The majority of these studies does not support, and some of them even refute, the bubble hypothesis suggesting that there is no direct link between commodity institutional investments and commodity prices. Nonetheless, the impact of financialisation on commodity price volatility, in the grain markets in particular, is still a source of concern both from an academic as well as a regulatory perspective^[Concerns over the consequences of financialisation were behind Rule 76 FR 4752 issued by the U.S. Commodity Futures Trading Commission (CFTC) on January 26, 2011. This provision emanates from the Dodd-Frank Wall Street and Consumer Protection Act of 2010 (Title VII, Section 737) that mandates the CFTC to use position limits to restrict the flow of speculative capital into a number of commodity markets. The Rule was approved in a close 3-2 vote and the ensuing rule-making process was extremely contentious with several commissioners expressing reservations about the lack of supporting evidence and the Rule also triggering thousands of comment letters as well as a lawsuit against the CFTC. See remarks of ex CFTC Chairman Gary Gensler before the International Monetary Fund Conference ([www.cftc.gov](http://www.cftc.gov/PressRoom/SpeechesTestimony/opagensler-137)) as well as remarks of Commissioner Bart Chilton ([www.cftc.gov](http://www.cftc.gov/PressRoom/SpeechesTestimony/chiltonstatement022412)).] and has not been thoroughly investigated yet^[@bohl_does_2013 is one of the few studies that investigate this issue.].  

In this study we examine the nature of this impact^[Our paper fits into the broad area of modeling changes in volatility and volatility transmission. See for example: @gannon_simultaneous_2010, @jiang_volatility_2017, @li_when_2016, @fung_information_2003, @smith_forecasting_2003, @nishina_nonlinear_2012.]. We focus on Chicago Board of Trade (CBOT) corn, soybeans and soft red winter wheat (SRW) as well as Kansas City Board of Trade (KCBOT) hard red winter wheat (HRW), four major global commodities of which the U.S. are a major producer. As financialisation is largely a U.S. based phenomenon it seems appropriate to study its effect on them. Besides, these markets are regarded as classic hedging markets where speculation tends to follow hedging volume [@working_hedging_1953; @working_whose_1954; @working_speculation_1960; @working_new_1962; @sanders_marginal_2012] and are thus good candidates for assessing the impact of financialisation, where speculation plays a central role. Also, the prices of these commodities tend to be driven by similar fundamentals as they can be substitutes and/or complements on the production and use sides. This makes it easier to isolate the effect of financialisation by examining the differences in volatility patterns before and during financialisation. Finally, corn, soybeans, HRW and SRW wheat are constituents of major commercial commodity indexes and are thus particularly suitable in this context.  

We study the volatility of the futures front month returns as well as that of the basis for each individual commodity considered over the 1992-2007 period using a set of volatility estimators that includes the classic ``close-to-close'' as well as a number of range-based estimators that account for intra-day price action. We define the 1992-2003 period as the pre-financialisation phase and the 2003-2007 as the financialisation phase with the 2003 cut-off based on earlier studies^[Most earlier studies locate the onset of financialisation around the 2003-2004 period [@basak_model_2016; @cheng_financialisation_2014; @hamilton_effects_2015; @irwin_index_2011; @irwin_financialisation_2012; @irwin_testing_2012; @tang_index_2012].]. We find a moderate increase in futures average volatility (from 10% to 25% depending on the estimator) and a much larger increase in basis average volatility (from 30% to over 100% depending on the estimator). Although uniform, the increase in average futures volatility is perhaps not as high as proponents of the Masters’ Hypothesis might have believed while that for basis volatility suggests potentially stronger effects due to financialisation.  

The relationship between volatility, volume and open interest has been investigated quite extensively in the finance literature with some studies suggesting that increases trading volume and open interest, via the entry of new traders, could have a stabilizing effect on volatility [@bessembinder_price_1993; @kyle_continuous_1985; @stoll_program_1987] while others, particularly in some recent studies, argue it could have a destabilizing effect [@goldstein_information_2015; @singleton_investor_2013; @sockin_informational_2015]. We investigate the issue by running regressions of volatility on contemporaneous and lagged volume and open interest.  

For futures volatility we observe an increase in $R^{2}$ over the financialisation period in most cases, sometimes dramatically^[The increase is largest for corn, followed by soybeans and HRW wheat. Results are mixed for SRW wheat.] as well as an overall increase in slope coefficient^[For SRW and HRW wheat both open interest and volume switch from negative (as predicted by @kyle_continuous_1985, @stoll_program_1987) to positive (as predicted by most informational models; @karpoff_relation_1987) during financialisation. For corn, open interest follows the same pattern while volume shows a positive relationship other the first period which gets stronger during financialisation. Soybeans show the opposite pattern with a negative correlation for both open interest and volume which becomes more negative during financialisation.] for both open interest and volume, contemporaneous and lagged. The pattern of results is similar for basis volatility. These results suggest that the relationship between volatility and both volume and open interest has changed and taken together with the large increase in level for both variables, suggest that financialisation has affected grains volatility. Open interest and volume seem to have switched from a stabilizing to a destabilizing role during financialisation for corn and both HRW and SRW wheat while for soybeans, the opposite seems to have happened. Overall our results suggest that increases in trading volume and open interest, a consequence of financialisation, appear to have had a destabilizing influence on grain volatility and seem consistent with the models of @stein_informational_1987^[He argues that entry of new traders could lower the information content of price for existing traders through noise in their signals.] @goldstein_information_2015^[They argue that the negative information content effect is caused by the behaviors of those traders who are informed of the same information but respond to this information in opposite directions. Their model suggests that commodity financialisation could make futures prices less informative (they refer to price informativeness as the amount of residual uncertainty uninformed traders face after conditioning on prices).], @singleton_investor_2013^[He notes that learning about economic fundamentals with heterogeneous information may induce excessive price volatility, drift in commodity prices, and a tendency towards booms and busts. He argues that under these conditions the flow of financial index investments into commodity markets may harm price discovery and social welfare.] and @sockin_informational_2015^[They develop a model to analyze information aggregation in commodity markets. Their analysis highlights important feedback effects of informational noise originating from supply shocks and futures market trading on commodity demand and spot prices.].  

We try to assess the impact of speculators by running similar regressions with open interest of hedgers and speculators separately as allowed by the U.S. Commodity Futures Trading Commission (CFTC)’s Commitment of Traders (COT) reports data^[A similar sort of analysis using the CFTC’s classification was carried out in @wang_behavior_2003. See the CFTC's explanatory notes for details on the traders classification in the COT legacy format: [www.cftc.gov](http://www.cftc.gov/MarketReports/CommitmentsofTraders/ExplanatoryNotes/index.htm)]. The results for speculators suggest a move towards a greater destabilizing effect for HRW wheat, corn and SRW wheat with no clear results for soybeans. The pattern is very similar for hedgers open interest which raises questions about the classification^[The CFTC has now refined its classification and publishes a ``disaggregated'' COT report with data going back to June 2006. In this report, the commercial category is further subdivided into processors/merchants and swap dealers while the non-commercial category is split into money managers and other reportables (not captured in the other groups). See the CFTC's explanatory notes for details on the traders classification in the COT disaggregated format:
[www.cftc.gov](http://www.cftc.gov/MarketReports/CommitmentsofTraders/DisaggregatedExplanatoryNotes/index.htm)] and perhaps the nature of hedgers’ activities^[See @cheng_why_2014.] and also suggests that these may have been influenced by financialisation. The pattern of results for basis volatility is very similar.  

We investigate the speculation issue further by running similar regressions with the Working's T index, a measure of excess speculation^[This measure originates in @working_speculation_1960 and is widely used in the agricultural economics literature to assess the impact of excess speculation.]. The results show no clear pattern across commodities or periods with both positive and negative slope coefficients in the second period. There is thus no clear indication that the change in relationship between volatility and open interest has been driven by excess speculation or an increase in speculative open interest. We conclude with a Granger causality analysis that we implement in turn on each pair of the above-mentioned variables. The results are generally inconclusive with some evidence that futures volatility and volume Granger cause each other and futures volatility Granger causes hedger's open interest in the second period.  

Overall our results point to an increase in grains volatility as well as a clear change in the relationship between grains volatility and open interest and volume as a result of financialisation. However there is no clear evidence that this change was driven by the actions of speculators. Our findings provide some support for the concerns of regulators but are overall more supportive of @goldstein_information_2015, @singleton_investor_2013 and @stein_informational_1987 in that disagreement and difference of opinion^[This issue is also of relevance in the recent legal literature [@stout_why_1998, @stout_uncertainty_2011] where it is referred to as disagreement based trading based on differing subjective beliefs about future prices. @stout_uncertainty_2011 shows how this may be viewed as a sort of market failure.] are more likely to have caused changes in the nature of grains volatility than excess speculation.  

The rest of the paper is organized as follow: the data and methods are described in the next section with the results discussed in section \ref{results}, while section \ref{conclusions} concludes.