# Results & discussion {#financialisation-grains-results}

Table 1 shows the mean futures front month and spot price levels, open interest and volume for the four commodities and two periods of interest. We observe a moderate increase of grain prices over the financialisation period with an average mean futures price increase of 11.7%; 10.5% for mean spot price. SRW wheat shows the strongest increase with +17.2% for mean futures price and +20.3% for mean spot price while corn shows the lowest with a 2% and 0.8% increase respectively. For the basis the situation is not as clear with the wheat complex showing a relative stability in numerical terms (+\$1.3 and +\$0.4 respectively) while corn and soybeans show dramatic increases (+\$6.4 or +138.5% and +\$8.7 or +264.7% respectively). In contrast to prices, mean open interest and volume show a dramatic increase across the board with average increase of 95.4% and 63.5% respectively suggesting that the large increase of trading activity during financialisation did not lead to a commensurate increase in grain prices.


Table 2 shows the average volatility levels for the four commodities and the two periods of interest. For futures average volatility, estimators include the classic "close-to-close" as well as the values for the five range-based estimators. The pattern of results is different across the various commodities and estimators but in all cases the average volatility is higher over the financialisation period with the average mean increase for the set of estimators ranging from 11.3% for SRW wheat to 20.1% for HRW wheat. For basis average volatility, estimators include the classic "close-to-close" as well as Parkinson and show a dramatic increase over the financialisation with the average increase for the two estimators ranging from 41.7% for SRW wheat to 155.6% for corn.  

Table 3 shows the results for the regressions of volatility on contemporaneous and one-week lagged volume and open interest. For futures volatility, the slope coefficients of open interest for corn and both types of wheat change to positive during financialisation from negative before indicating open interest changes from having a stabilizing effect on volatility in the first period consistent with a classic hedging market [@working_speculation_1960; @working_new_1962] to a destabilizing effect in the second for these commodities. The $R^{2}$s vary across the two periods with a sharp increase for corn (11% to 44%) and a decrease for HRW wheat (28% to 5%) suggesting that while the nature of the effect is uniform for the three commodities, the magnitude is not. For soybeans the sign of all slope coefficients is negative in both periods and the $R^{2}$ is higher in the financialisation period indicating a greater stabilizing effect. The pattern and magnitude of the results is very similar when lagged open interest is used, suggesting that it is the expected component of open interest that is driving these results [@bessembinder_price_1993]. For volume, the slope coefficients switch from negative to positive for SRW & HRW wheat while, in both periods, they are positive for corn with a substantially higher $R^{2}$ over the financialisation period (2.8% to 24.2% for the Yang & Zhang estimator) and negative for soybeans with again a higher $R^{2}$ in the financialisation phase. The pattern is very similar for lagged volume indicating that the results are driven by expected volume. The pattern of results is thus similar for both open interest and volume and indicates that over financialisation they had a destabilizing effect on futures volatility for corn and the two types of wheat while having a more stabilizing effect for soybeans. Besides, soybeans showed the most pronounced increase in average futures volatility indicating that changes in the nature of volatility and the changes in the magnitude of volatility are not necessarily directly linked.
Overall these findings provide evidence for the hypotheses advanced in @goldstein_speculation_2014, @singleton_investor_2013 and @stein_informational_1987 where more trading arising from greater dispersions of beliefs or the entry of new traders increasing noise in signals could lead to changes in the nature of volatility and the information content of prices. Thus greater market depth may not always lead to more informative price signals and this may be due to the nature of trading (see also @stout_why_1998 & @stout_uncertainty_2011) for a discussion of this issue from a legal standpoint).
For basis volatility there does not appear to be a clear pattern and the results suggest that the nature of basis volatility is different from that of futures, with other factors perhaps driving the increases.  


Combining volume and open interest produces a mixed pattern of results as shown in table 4. For futures volatility, corn and SRW wheat show a change in sign and increase in $R^{2}$ (Yang & Zhang estimator) during financialisation while for HRW wheat, there is a change in sign for the open interest slope coefficient with the coefficient for volume positive in both periods and a lower $R^{2}$ for the financialisation period. These results suggest that both factors jointly had a destabilizing influence on volatility. For soybeans, the two coefficients are negative in both periods with a higher $R^{2}$ for the financialisation period indicating a greater stabilizing effect. The results for the four-factor model are shown in table 5. The clearest pattern is for corn where the $R^{2}$ for the Yang & Zhang estimator model increase from 18% pre-financialisation to 44% during the financialisation phase.  


Table 6 shows the results for the Granger causality analysis where we observe a change in behavior between the two periods. For SRW wheat and corn open interest Granger causes volatility (Yang & Zhang estimator), but not the other way round, in the pre-financialisation period during financialisation period the only causal relation established is for SRW wheat volatility (Yang & Zhang estimator) Granger causing volume. In contrast, over the same period, for HRW wheat, the smallest market, and soybeans, volume appears to Granger cause volatility. There is thus no clear pattern over the financialisation period and the evidence is stronger in the first period for volume Granger causing volatility. Taken together these results provide further confirmation for a change in relationship between volatility and both volume and open interest, with some evidence that financialisation may have driven volatility higher in the smallest grain market.  


The mean Working's T index levels range from 1.05 (HRW wheat) to 1.18 (SRW wheat) over the first period while they range from 1.08 (HRW wheat) to 1.18 (SRW wheat) over the second period. The results indicate a very limited mean level increase from the first to the second period, 1.9% on average across commodities, ranging from no change for SRW wheat to a 2.9% increase for HRW wheat, suggesting that the level of ``excess speculation'' as defined by Working (1960) did not uncouple with historical levels during financialisation^[As suggested in @sanders_speculative_2010.].  


Table 7 shows the results for the regressions of volatility on contemporaneous and one-week lagged total open interest, open interest of speculators, open interest of hedgers, volume and Working's T index. The pattern of results is very similar for both the open interest of hedgers and speculators in both periods indicating that the influence of hedgers and speculators on volatility is very similar and did not change over financialisation. For SRW wheat, the slope coefficients for both hedgers and speculators are positive in both periods indicating a destabilizing effect, with a higher $R^{2}$ in the second period suggesting a greater destabilizing effect. The results for corn indicate a change from stabilizing, with both coefficients negative pre-financialisation, to destabilizing with positive coefficients during financialisation accompanied by a sharp increase in $R^{2}$. For HRW wheat, the evidence is mixed with some evidence of a greater stabilizing influence for both hedgers and speculators while for soybeans all slope coefficients are negative but with lower $R^{2}$ during financialisation indicating a weaker stabilizing influence. The overall thrust of the evidence is towards a greater destabilizing influence of open interest on volatility with little difference between hedgers and speculators. These findings echo some of the issues raised in @cheng_why_2014 and raises issues about the classification system used by the CFTC. The results for basis volatility are similar except for HRW wheat for which open interest shows a trend towards greater destabilization influence on volatility. The results for the Working's T index provide no clear support for the hypothesis that excess speculation may have caused changes in the nature of commodity futures volatility. The slope coefficient for corn switches from positive to negative indicating that "excess speculation" seemed to have a stabilizing influence on volatility during financialisation. The results are mixed for wheat with a switch from stabilizing to destabilizing for SRW wheat and negative coefficients in both periods for HRW wheat albeit with lower $R^{2}$ over financialisation while for soybeans there is evidence of a greater destabilizing effect. These results further reinforce the hypothesis that dispersion in beliefs or disagreement-based trading [@stout_uncertainty_2011] could be one of the driving forces behind some of the effects observed over the financialisation phase. For basis volatility there is no clear pattern with five out of eight coefficients negative for the financialisation period.  


Table 8 shows the results for a four-factor model where the response is volatility and the explanatory variables include contemporaneous and one-week lagged open interest of hedgers, open interest of speculators, volume and Working's T index. The results are strongest for corn with a dramatic increase in $R^{2}$ (20.9% to 52.2%) while all the others results are mixed, reinforcing the earlier findings above indicating that the effects of financialisation seem to have been most pronounced in the corn market.


The results of the Granger causality analysis are shown in Table 9 and are generally inconclusive with the only clear evidence for SRW wheat where futures volatility and volume Granger cause each other and futures volatility Granger causes open interest of hedgers over the financialisation period.

