# Conclusion {#conclusions}

Institutional investments in long-only commodity index funds soared in the early 2000s which led to a large increase in trading activity as measured by open interest and volume. This surge and its attendant impacts are commonly referred to as the ``financialization'' of commodity markets. In this paper, we investigate the effect of financialization on the volatility of grain futures markets. These markets have been classically regarded as hedging markets and have been at the forefront of the debate over whether financialization has contributed to price and volatility spikes. We find that all grains futures volatility increased in the period of financialization but that this increase is not as large as commonly believed. Nonetheless, we find that the increase in market depth has a generally destabilizing effect on grains volatility but that this destabilizing effect does not seem to be driven by the action of speculators. Our results generally support the findings of @stein_informational_1987, @goldstein_speculation_2014, @singleton_investor_2013, and @sockin_informational_2015 which suggest that increased market depth that arises as a result of difference of opinion between traders could lower the information content of prices. Our results therefore add to the growing body of evidence that suggest that greater market depth may not always have a beneficial effect on markets.  

